name = "JMarkovJunior"
uuid = "1327bbcd-95f5-4c5d-be2a-0189b406575c"
authors = ["William Mishra-Manning <manning.w27@gmail.com>"]
version = "0.1.0"

[deps]
Bplus = "c71c5366-3533-40c3-bcf3-6383cd1eb1eb"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
CImGui = "1.82.0"
CSyntax = "0.4.1"
ColorTypes = "0.12.1"
Colors = "0.13.1"
GLFW = "3.4.1"
ImageIO = "0.6.9"
Images = "0.26.2"
OrderedCollections = "1.8.1"
Random = "1.11.0"
Setfield = "1.1.2"
